name: sika
description: "Sistem Informasi Karyawan Kasih Ibu"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  camera: ^0.11.0+2
  connectivity_plus: ^6.1.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.2
  location: ^7.0.1
  permission_handler: ^11.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/

flutter_launcher_icons:
  image_path: "assets/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  background_color: "#ffffff"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.png"
